### ISSUE TITLE
Source Replacement not working

### ISSUE THREAD

**Issue by litzh** [nabijaczleweli/cargo-update#107]
```
$ cargo version
cargo 1.37.0 (9edd08916 2019-08-02)
$ cargo install-update --version
cargo-install-update 1.7.0
```

According to [The Cargo Book](https://doc.rust-lang.org/cargo/reference/source-replacement.html), Cargo supports the ability to replace one source with another.

Below is my `~/.cargo/config`:
```toml
[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"
replace-with = 'ustc'
[source.ustc]
registry = "git://mirrors.ustc.edu.cn/crates.io-index"
```

When executing `cargo install`,  Cargo downloads from custom source.
```
$ cargo install cargo-update
    Updating `git://mirrors.ustc.edu.cn/crates.io-index` index
```
When executing `cargo install-update`, Cargo downloads from the default source.
```
$ cargo install-update -a
    Updating registry 'https://github.com/rust-lang/crates.io-index'
```
