### ISSUE TITLE
Alternate registry broken

### ISSUE THREAD

**Issue by DCjanus** [nabijaczleweli/cargo-update#137]
Because of network block in China, I'm using a public proxy for `crates.io` in China, and found broken behavior:

![图片](https://user-images.githubusercontent.com/15802727/88680011-a37a0e80-d122-11ea-9ba7-a701998c4bb8.png)

Here is my config file:

```toml
[source.crates-io]
replace-with = "sjtu"

[source.sjtu]
registry = "https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index"
```

I was trying to found root cause of this, but I failed, if there is any help, would be great.

PS: remove 'replace-with' and update my packages from official registry, and put `replace-with` back, nothing happend.
