### ISSUE TITLE
cargo config http.proxy caused the error:malformed URL '127.0.0.1:1080'

### ISSUE THREAD

**Issue by zx950921** [nabijaczleweli/cargo-update#144]
my cargo .cargo/config:
```toml
[http]
proxy = "127.0.0.1:1080"

[https]
proxy = "127.0.0.1:1080"
```

I use "cargo update" and "cargo install" to pass the proxy normally.No problem with proxy service.
But when using "cargo install-update -a" an error occurs directly, the error content is
```bash
~$ cargo install-update -a
     Updating registry'https://github.com/rust-lang/crates.io-index'
Failed to update index repository: malformed URL '127.0.0.1:1080'.
```

rust version is:
```bash
   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.46.0 (04488afe3 2020-08-24)
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.48.0-nightly (f3c923a13 2020-09-17)
```
cargo version is:cargo 1.48.0-nightly (8777a6b1e 2020-09-15)

**Comment by nabijaczleweli** [comment]
Hm, this is correct: "127.0.0.1:1080" is not a valid URL and libgit2 is right to reject it here. A better question is how Cargo mangles the values.

**Comment by zx950921** [comment]
```toml
[http]
proxy = "http://127.0.0.1:1080"

[https]
proxy = "https://127.0.0.1:1080"
```

I change the config file to this,it work well.

The doc of this is: [doc](https://doc.rust-lang.org/cargo/reference/config.html#httpproxy)

I didn't notice this detail before, The complete http proxy configuration should be "[protocol://]host[:port]"

Thanks for helping
