### ISSUE TITLE
Cannot fetch updates from non-crates source

### ISSUE THREAD

**Issue by tranzystorek-io** [nabijaczleweli/cargo-update#160]
Here's the output from `cargo install-update -a`:

```console
    Updating registry 'https://dl.cloudsmith.io/public/tranzystorek-crates/default/cargo/index.git'

    Updating registry 'https://github.com/rust-lang/crates.io-index'

Package       Installed  Latest  Needs update
pakr          v0.2.2     v0.3.0  Yes
cargo-update  v7.0.1     v7.0.1  No
flamegraph    v0.4.0     v0.4.0  No

Updating pakr
error: no index found for registry: `tranzystorek_crates`


Updated 0 packages.
Failed to update pakr.
```

My `~/.cargo/config`:

```toml
[registries]
tranzystorek-crates = { index = "https://dl.cloudsmith.io/public/tranzystorek-crates/default/cargo/index.git" }

[source.tranzystorek_crates]
registry = "https://dl.cloudsmith.io/public/tranzystorek-crates/default/cargo/index.git"
```
