### ISSUE TITLE
cargo install-update report `error: no index found for registry`

### ISSUE THREAD

**Issue by viruscamp** [nabijaczleweli/cargo-update#185]
`cargo install-update` report `error: no index found for registry`  
but `cargo install` success.

```
>cargo install-update bat
    Updating registry 'https://rsproxy.cn/crates.io-index'

Package  Installed  Latest   Needs update
bat      v0.18.3    v0.21.0  Yes

Updating bat
error: no index found for registry: `rsproxy`


Updated 0 packages.
Failed to update bat.
>cargo install bat

Replaced package `bat v0.18.3` with `bat v0.21.0` (executable `bat.exe`)
```

That is my cargo\config
```toml
[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"

replace-with = 'rsproxy'

[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"
```
