### ISSUE TITLE
Follow install.root

### ISSUE THREAD

**Issue by jan-hudec** [nabijaczleweli/cargo-update#23]
`cargo install-update -l -a` simply finds no packages for me. I suspect it fails to read the `~/.cargo/config` where the installation directory is redirected to where it is supposed to be:

```toml
[install]
root = "/home/me/.local"
```
