### ISSUE TITLE
Failure when using source replacement

### ISSUE THREAD

**Issue by cyqsimon** [nabijaczleweli/cargo-update#247]
When a [source replacement](https://doc.rust-lang.org/cargo/reference/source-replacement.html) is specified for crates.io in `~/.cargo/config.toml`, updating using `cargo install-update -a` will fail:

```
Updating PKG
error: registry index was not found in any configuration: `SOURCE`
```

## Steps to reproduce

1. Append the following to `~/.cargo/config.toml`:

```toml
[source.my-replacement-source]
registry = "https://github.com/jhnc-oss/crates.io-index.git"
[source.crates-io]
replace-with = "my-replacement-source"
```

You can use any valid registry; I just picked the most recent GitHub fork of https://github.com/rust-lang/crates.io-index.

2. Run `cargo install fd-find@8.6.0` to verify the registry setting. Again, you can use any valid binary crate.
3. Run `cargo install-update -l` to verify that `fd-find` has an update.
4. Run `cargo install-update -a` and observe the failure.
5. Don't forget to reset `~/.cargo/config.toml` after testing.
