### ISSUE TITLE
error: registry index was not found in any configuration: `rsproxy-sparse`

### ISSUE THREAD

**Issue by kzhui125** [nabijaczleweli/cargo-update#248]
```sh
cargo install-update -a
    Polling registry 'https://rsproxy.cn/index/'.......

Package           Installed  Latest   Needs update
cargo-expand      v1.0.71    v1.0.75  Yes
cargo-generate    v0.18.4    v0.19.0  Yes
cargo-leptos      v0.1.11    v0.2.5   Yes
mdbook            v0.4.35    v0.4.36  Yes
cargo-update      v13.3.0    v13.3.0  No
mdbook-linkcheck  v0.7.7     v0.7.7   No
wasm-bindgen-cli  v0.2.89    v0.2.89  No

Updating cargo-expand
error: registry index was not found in any configuration: `rsproxy-sparse`

Updating cargo-generate
error: registry index was not found in any configuration: `rsproxy-sparse`

Updating cargo-leptos
error: registry index was not found in any configuration: `rsproxy-sparse`

Updating mdbook
error: registry index was not found in any configuration: `rsproxy-sparse`


Updated 0 packages.
Failed to update cargo-expand, cargo-generate, cargo-leptos, mdbook.
```

while when i run `cargo install cargo-expand` manually, it works.

my `~/.cargo/config` file:

```toml
[source.crates-io]
replace-with = 'rsproxy-sparse'

[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"

[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"

[registries.rsproxy]
index = "https://rsproxy.cn/crates.io-index"

[net]
git-fetch-with-cli = true
```

**Comment by iKunCai** [comment]
Same error here.

**Comment by nabijaczleweli** [comment]
Dupe of #247 (#185), documented in https://github.com/nabijaczleweli/cargo-update#source-replacement-vs-custom-registries: if you have a `registry` key you need to also have an `index` key –
```toml
[source.crates-io]
replace-with = 'rsproxy-sparse'

[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"
index = "https://rsproxy.cn/crates.io-index"

[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"
index = "sparse+https://rsproxy.cn/index/"

[registries.rsproxy]
index = "https://rsproxy.cn/crates.io-index"

[net]
git-fetch-with-cli = true
```

**Comment by liebkne** [comment]
I copy the config you pasted, but still not work for me

```
user@macos:~ $ cia
    Polling registry 'https://rsproxy.cn/index/'.............................................

Package             Installed  Latest                               Needs update
tenere              v0.10.0    v0.11.0                              Yes
trunk               v0.18.7    v0.18.8 (v0.19.0-alpha.2 available)  Yes
aichat              v0.12.0    v0.12.0                              No
bat                 v0.24.0    v0.24.0                              No
blackd-client       v0.1.0     v0.1.0                               No
bottom              v0.9.6     v0.9.6                               No
cargo-binstall      v1.6.2     v1.6.2                               No
cargo-cache         v0.8.3     v0.8.3                               No
cargo-clean-all     v0.6.2     v0.6.2                               No
cargo-edit          v0.12.2    v0.12.2                              No
cargo-leptos        v0.2.7     v0.2.7                               No
cargo-quickinstall  v0.2.10    v0.2.10                              No
cargo-rx            v0.3.0     v0.3.0                               No
cargo-update        v13.3.0    v13.3.0                              No
cargo-watch         v8.5.2     v8.5.2                               No
du-dust             v0.9.0     v0.9.0                               No
dua-cli             v2.28.0    v2.28.0                              No
erdtree             v3.1.2     v3.1.2                               No
exa                 v0.10.1    v0.10.1                              No
fd-find             v9.0.0     v9.0.0                               No
git-cliff           v1.4.0     v1.4.0                               No
grex                v1.4.4     v1.4.4                               No
huniq               v2.7.0     v2.7.0                               No
hurl                v4.2.0     v4.2.0                               No
hyperfine           v1.18.0    v1.18.0                              No
hysp                v0.1.2     v0.1.2                               No
jaq                 v1.3.0     v1.3.0                               No
jless               v0.9.0     v0.9.0                               No
just                v1.23.0    v1.23.0                              No
kondo               v0.8.0     v0.8.0                               No
leptosfmt           v0.1.18    v0.1.18                              No
milkbox             v0.0.7     v0.0.7                               No
navi                v2.23.0    v2.23.0                              No
ouch                v0.5.1     v0.5.1                               No
pylyzer             v0.0.51    v0.0.51 (v0.1.0-beta.0 available)    No
ripgrep             v14.1.0    v14.1.0                              No
runfile             v0.1.1     v0.1.1                               No
spider_worker       v1.82.2    v1.82.2                              No
tealdeer            v1.6.1     v1.6.1                               No
tokei               v12.1.2    v12.1.2 (v13.0.0-alpha.0 available)  No
topgrade            v14.0.1    v14.0.1                              No
treegrep            v0.1.3     v0.1.3                               No
wasm-pack           v0.12.1    v0.12.1                              No
zellij              v0.39.2    v0.39.2                              No
zoxide              v0.9.2     v0.9.2                               No

Updating tenere
error: registry index was not found in any configuration: `rsproxy-sparse`

Updating trunk
error: registry index was not found in any configuration: `rsproxy-sparse`


Updated 0 packages.
Failed to update tenere, trunk.
```

**Comment by nabijaczleweli** [comment]
Reduces to `cargo install --registry rsproxy-sparse tenere` and I can repro this.
I misread the documentation in https://github.com/nabijaczleweli/cargo-update/tree/1ef224e1611045cbdbd0cc1404ce05f37133edac#source-replacement-vs-custom-registries, you need to add
```toml
[registries.rsproxy-sparse]
index = "sparse+https://rsproxy.cn/index/"
```
for a result of
```toml
[source.crates-io]
replace-with = 'rsproxy-sparse'

[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"

[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"

[registries.rsproxy]
index = "https://rsproxy.cn/crates.io-index"

[registries.rsproxy-sparse]
index = "sparse+https://rsproxy.cn/index/"

[net]
git-fetch-with-cli = true
```
(note how OP's config already had `registries.rsproxy`)
