### ISSUE TITLE
Support custom profile

### ISSUE THREAD

**Issue by Berrysoft** [nabijaczleweli/cargo-update#282]
A default custom profile could be defined in `~/.cargo/config.toml`, for example,
```toml
[profile.release-lto]
inherits = "release"
lto = true
codegen-units = 1
```
I would like to configure cargo-update to use a custom profile for specific installed crate.
